language: ruby
rvm:
- jruby-1.7.20
before_install:
- gem install bundler -v 1.10.1
- sudo rm -rf /etc/apt/sources.list.d/couchdb-ppa-source.list
- sudo rm -rf /etc/apt/sources.list.d/mongodb.list
- sudo rm -rf /etc/apt/sources.list.d/datastax-source.list
- sudo rm -rf /etc/apt/sources.list.d/rabbitmq-source.list
- sudo rm -rf /etc/apt/sources.list.d/mapopa-source.list
- sudo rm -rf /etc/apt/sources.list.d/webupd8team-java-ppa-source.list
- sudo rm -rf /etc/apt/sources.list.d/maven3-ppa-source.list
- wget -O- http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -
- echo deb http://packages.couchbase.com/ubuntu precise precise/main | sudo tee /etc/apt/sources.list.d/couchbase.list
- sudo apt-get update
- sudo apt-cache search libcouchbase
- wget http://packages.couchbase.com/releases/3.0.3/couchbase-server-enterprise_3.0.3-ubuntu12.04_amd64.deb
install:
- sudo apt-get -y install libcouchbase-dev libcouchbase2-libevent
#- sudo apt-get -y install libcouchbase2-dev
- sudo dpkg -i couchbase-server-enterprise_3.0.3-ubuntu12.04_amd64.deb
#- sudo service couchbase-server start
- sudo netstat -anp  | grep 8091
- sudo /opt/couchbase/bin/couchbase-cli cluster-init -c localhost:8091 --cluster-init-username=Administrator --cluster-init-password=password --cluster-init-ramsize=256
- sudo /opt/couchbase/bin/couchbase-cli bucket-create -c localhost:8091 --bucket=default --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=100 --bucket-replica=0 -u Administrator -p password
script: bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure: BOC9COQ83ni6mYN5d2nqzFPiBXyFuIyQObEMACBZk2Ts9QvoMdmuG265VS8rC1cKXughq82gWVFk1MIEstseXFT2szRSx/pani3tSjPsXz/xPGP7GTOtcgSxXsWbblqZ4y2mpR+8WOtg1Ad/B6nM/smyChcrZ9xE2hbhgY0JsdUxifOUZ38H+aDBAaMrs/EAq2Ar47YVQsqPgvCfGyHBQRz2mNg6l8o++0AYzsqG9zICwVoyHI9j/XEhBbYg0E8Cs6GwQH3FofFgBOpPFKLFIP32LTSn+tU1IOoldDhgyOTWEz1M4G4E/Td2xrv8tw0xVGbWf5s3hCMmYlNQc4QRDvjEvTouZRgjEFigKjM0qS4C5piY54jv1ARSyhNOvoz37/M9eaPDcFBwiyREMW8GqMqo+BbTWGWsAoqW/hmOKwfTaQ5AuCRlyHtGwRvxyeiMTgyutA3pQEVc4dY8H8l6QM2HGHJyjIhxgUa2LZgUg+yeIQ97/MFeBbBFwSLEwJIwYiWEtA6UhS003n5J2AVop8y/Imf9iugZbTPbHqf6wbsrlJsaj80TJCvc1MITHiPMazCmWN2/jA5ts+eYUiSXhfmawY1ekVvsqZJ3de6lCu9AExXZBktCk3qKcn73rEM/e1JJOybcvUiHsFD1SQjKttHCEo3uKp3vUpwcd7nvJrE=
after_success:
- coveralls
addons:
  code_climate:
    repo_token:
      secure: rTDqQz0FiN3CCsh9mnNObhnnQiOaFRfW3NZwMT1BjdP3Bxqb9b1V1Ino62x9sj5dkB5uckfUqCSkoJHeNPQbooccLpCGei5KIsu7j+UmYfnFFJTpZ+idVpHsHN6AsuLRuKuj7XtSWYT7Y0M9i14EWMzVrcp5CoDfSbwIBnzb24GU3F8rx797QQYPGqNSzU9pJ3iK2Vs2Z/61iOEvJQbFCSTslP3Zt3239/I3rB9Pv6whGbVj4h/Omq+f1GnHZWjYZ4q9OTvHI+JE8pj694EOvJnU/rC/bckMDAQI+WUj6mLbpFZXqDsNAeJuALuXpyuAH/kumqCSv9zYpE1cXqgPYni8+pV/R7BhvO0KQGNx15OY2hhDadDyBHGfoQZ6AKbXkENLMcInhazFQsec7QEaJREFya/buMBZyeGbvz3npj15psnfAGCDij2f6otS3TSWB47SN6RMnhHIRxu/B+HF5FBlr+N0Xg43DozfqpfWGkQ3qNwOhMwZuFlTkG/mINsDvINLx5FL+5JsTcDGpssUBL2+vw+dAb7IRB5FdWx4nXnYiaeSGJ30EOHiRaz7tFzite8iqmKMWD4j7eadM48Qa2D8weYkCLsEsLIbb2QtEy24Fpb7kMe7t2+TdSxMVD+b6GmHn73QfrYmS8coEA6VuuQKUdcIugkZ5+8rENWem0k=
cache: bundler
